version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    
  - package-ecosystem: "docker"
    directory: "packages/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
