version: '3.9'
services:
  database:
    image: postgres:16.0-alpine
    restart: always  
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432' 
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
    driver: local 