name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      uploadToRegistry:
        description: 'Upload to Docker Hub'
        required: true
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies and build
      run: |
        yarn install --frozen-lockfile
        yarn tsc
        yarn build:backend --config ../../app-config.yaml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: github.event.inputs.uploadToRegistry == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event.inputs.uploadToRegistry == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: packages/backend/Dockerfile
        push: ${{ github.event.inputs.uploadToRegistry == 'true' }}
        tags: visakh/backstage-experiments:latest

    - name: Log out of Docker Hub
      if: github.event.inputs.uploadToRegistry == 'true'
      run: docker logout
